### ISSUE TITLE
Can bna work with npm v3?

### ISSUE THREAD

**Issue by birbird** [mhzed/bna#1]
We use bna in an old system. We decided to upgrade nodejs from v4 to v6, but found it fail.

One major change of npm v3 (default npm version in nodejs v6) is it installs secondary dependencies (dependencies of dependencies) in a flat way if possible. While npm v2 (default npm version in nodejs v4) installs all dependencies in a nested way. see ​https://docs.npmjs.com/how-npm-works/npm3

bna seems make the assumption that dependencies in node_modules are nested.
Is this true and can it cause the problem?

**Comment by mhzed** [comment]
Surprised and happy to hear someone is actually using this!!

In theory the flat hierarchy should not make a difference, bna makes no assumption on how packages in node_modules are laid out in filesystem.  In practice there are always bugs though.  If you can create a reproduce-able series of steps to demonstrate the problem, then I can take a look and try to fix it.

**Comment by birbird** [comment]
Sorry for the late response.
Here I can give a package.json to reproduce the error
```
{
  "name": "bna-test",
  "dependencies": {
    "assetsmanager-brunch": "*",
    "async": "1.3.0",
    "auto-launch": "2.0.1",
    "blueimp-md5": "*",
    "bytes": "*",
    "chmodr": "*",
    "connect": "2.14.3",
    "connect-cors": "*",
    "copy-paste": "*",
    "cookie-signature": "*",
    "del": "*",
    "diskspace": "0.1.7",
    "event-stream": "*",
    "express": "4.11.1",
    "filed": "*",
    "fs-extra": "0.11.1",
    "mime": "*",
    "ms": "*",
    "multiparty": "4.1.2",
    "mustache": "*",
    "open": "*",
    "request": "*",
    "shasum": "*",
    "socket.io-client": "1.4.5",
    "ssh2": "0.4.8",
    "udid": "dominictarr/udid",
    "universal-analytics": "*",
    "unzip": "*",
    "url": "*",
    "debug": "1.0.4",
    "log": "*",
    "connect-cors": "*",
    "ncp": "2.0.0",
    "sqlite3-transactions": "*",
    "gm": "*",
    "default-network": "*",
    "uuid": "*",
    "lodash": "*",
    "brunch": "1.7.14",
    "coffee-script": "~1.9",
    "json": "*",
    "stylus": "0.32.x",
    "javascript-brunch": ">= 1.0 < 1.6",
    "uglify-js-brunch": ">= 1.0 < 1.6",
    "coffee-script-brunch": "~1.8",
    "stylus-brunch": "~1.6.1",
    "css-brunch": "~1.5.1",
    "jade-brunch": "~1.7.2",
    "static-jade-brunch": "1.4.11",
    "jade": "~0.35.0",
    "mocha": "*",
    "assert": "*",
    "should": "*",
    "supertest": "*",
    "auto-reload-brunch": "1.8.1",
    "bna": "1.0.6",
    "dive": "*"
  }
}
```

npm install on this package.json, then
/node_modules/.bin/bna --fuselib ./node_modules/ -o lib.js

if the npm is v2, success, if the npm is above v2, fail, due to "esprima failed to parse due to: Error: Line 42: Unexpected reserved word"

**Comment by mhzed** [comment]
It seems your bna version was very old.  The newest version use 'acorn' instead of 'esprima' as the parser.  
I've run the newest bna against your example.  There were a few warnings but a 17M output file is generated successfully.

**Comment by birbird** [comment]
I tested it with bna 2.03. It's another error

[Dec 30 2016 07:47:27.697 GMT-0500] Generating lib.js 
/root/work/bna-test/node_modules/winreg/test.js.bna.js:43
            .   get(items[0].name, function (err, item) {
                         ^

TypeError: Cannot read property '0' of undefined
  at /root/work/bna-test/node_modules/winreg/test.js.bna.js:43:26
  at ChildProcess.<anonymous> (/root/work/bna-test/node_modules/winreg/lib/registry.js:461:5)
  at emitOne (events.js:96:13)
  at ChildProcess.emit (events.js:188:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
  at onErrorNT (internal/child_process.js:359:16)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)


node: v6.9.1
npm: 4.0.5
bna: 2.0.3

**Comment by mhzed** [comment]
In short this error does not affect the output and can be ignored.

Error is thrown by /root/work/bna-test/node_modules/winreg/test.js, it's 'executed' by bna because it requires a non string literal (thus bna will evaluate code to resolve the actual required file).

**Comment by birbird** [comment]
Thanks a lot.
